--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cooldogedev/BedrockEconomy
build-by-default: true
branches:
- main
projects:
  BedrockEconomy:
    path: ""
    libs:
      - src: cooldogepm/libSQL/libSQL
        version: ^0.1.2
        branch: main
      - src: cooldogepm/Commando/Commando
        version: ^3.1.2
    lint:
      phpstan: false
#      syntaxError: false
...


